name: Run Python Script

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 1 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script
              id: claim
              env:
                  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
                  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
                  ACCOUNTS1: ${{ secrets.ACCOUNT1 }} # 859
                  ACCOUNTS2: ${{ secrets.ACCOUNT2 }} # Muad
                  ACCOUNTS3: ${{ secrets.ACCOUNT3 }} # albaly
              run: python main.py -o -t
