name: Run Python Script

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 1 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script
              id: claim
              env:
                  ACCOUNTS1: ${{ secrets.ACCOUNT1 }} # 859
                  ACCOUNTS2: ${{ secrets.ACCOUNT2 }} # Muad
                  ACCOUNTS3: ${{ secrets.ACCOUNT3 }} # albaly
              run: echo python main.py -o >> $GITHUB_OUTPUT
              
            - name: send telegram message on push
              uses: appleboy/telegram-action@master
              env:
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              with:
                to: ${{ secrets.TELEGRAM_TO }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                disable_web_page_preview: true
                message: |
                  Repository: *${{ github.repository }}*
                  Owner: *${{ github.repository_owner }}*
                  Output:
                  ```
                  ${{ steps.claim.conclusion }}
                  ```
                  
                  ```
                  ${{ steps.claim.outputs }}
                  ```
